<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory
{
    public function getActiveJobs($max = 10)
    {
      // $max = sfConfig::get('app_max_jobs_on_category');
      $q = $this->getActiveJobsQuery()
        ->limit($max);
     
      return $q->execute();
    }

    public function getLatestPost()
    {
      return $this->getActiveJobs(1)->getFirst();
    }

    public function getActiveJobsQuery()
    {
      $q = Doctrine_Query::create()
        ->from('JobeetJob j')
        ->where('j.category_id = ?', $this->getId());
     
      return Doctrine_Core::getTable('JobeetJob')->addActiveJobsQuery($q);
    }



    /**
     * count no. of active jobs
    * @return Integer
    */
    public function countActiveJobs()
    {
      return $this->getActiveJobsQuery()->count();
    }
    
}