<?php

/**
 * BaseJobeetJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $type
 * @property string $company
 * @property string $logo
 * @property string $url
 * @property string $position
 * @property string $location
 * @property string $description
 * @property string $how_to_apply
 * @property string $token
 * @property boolean $is_public
 * @property boolean $is_activated
 * @property string $email
 * @property timestamp $expires_at
 * @property JobeetCategory $JobeetCategory
 * 
 * @method integer        getcategory_id()    Returns the current record's "category_id" value
 * @method string         gettype()           Returns the current record's "type" value
 * @method string         getcompany()        Returns the current record's "company" value
 * @method string         getlogo()           Returns the current record's "logo" value
 * @method string         geturl()            Returns the current record's "url" value
 * @method string         getposition()       Returns the current record's "position" value
 * @method string         getlocation()       Returns the current record's "location" value
 * @method string         getdescription()    Returns the current record's "description" value
 * @method string         gethow_to_apply()   Returns the current record's "how_to_apply" value
 * @method string         gettoken()          Returns the current record's "token" value
 * @method boolean        getis_public()      Returns the current record's "is_public" value
 * @method boolean        getis_activated()   Returns the current record's "is_activated" value
 * @method string         getemail()          Returns the current record's "email" value
 * @method timestamp      getexpires_at()     Returns the current record's "expires_at" value
 * @method JobeetCategory getJobeetCategory() Returns the current record's "JobeetCategory" value
 * @method JobeetJob      setcategory_id()    Sets the current record's "category_id" value
 * @method JobeetJob      settype()           Sets the current record's "type" value
 * @method JobeetJob      setcompany()        Sets the current record's "company" value
 * @method JobeetJob      setlogo()           Sets the current record's "logo" value
 * @method JobeetJob      seturl()            Sets the current record's "url" value
 * @method JobeetJob      setposition()       Sets the current record's "position" value
 * @method JobeetJob      setlocation()       Sets the current record's "location" value
 * @method JobeetJob      setdescription()    Sets the current record's "description" value
 * @method JobeetJob      sethow_to_apply()   Sets the current record's "how_to_apply" value
 * @method JobeetJob      settoken()          Sets the current record's "token" value
 * @method JobeetJob      setis_public()      Sets the current record's "is_public" value
 * @method JobeetJob      setis_activated()   Sets the current record's "is_activated" value
 * @method JobeetJob      setemail()          Sets the current record's "email" value
 * @method JobeetJob      setexpires_at()     Sets the current record's "expires_at" value
 * @method JobeetJob      setJobeetCategory() Sets the current record's "JobeetCategory" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseJobeetJob extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_job');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('company', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('position', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '4000',
             ));
        $this->hasColumn('how_to_apply', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '4000',
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JobeetCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}